In [1]:
import numpy as np
x = np.array([0,1,2])
y = np.array([2,1,0])
print("n\Original array1:")
print (x)
print("n\Original array1")
print(y)
print("\Covariance matrix of the said array:\n",np.cov(x,y))

n\Original array1:
[0 1 2]
n\Original array1
[2 1 0]
\Covariance matrix of the said array:
 [[ 1. -1.]
 [-1.  1.]]
